@startuml architecture

component core {
	package bank.core
}

component persistence {
	package bank.persistence
}

component jackson {
    component jackson.databind
}

bank.persistence ..> jackson.databind
bank.persistence ..> bank.core

component ui {
	package bank.ui
}

component javafx {
	component javafx.fxml
    component javafx.controls
}

component java.net {
	component java.net.http
}

bank.ui ..> bank.core
bank.ui ..> bank.persistence
bank.ui ..> javafx.fxml
bank.ui ..> javafx.controls
bank.ui ..> jackson.databind

component rest {
	package bank.rest
}

component spring {
  component spring.web
  component spring.beans
  component spring.boot
  component spring.context
  component spring.webmvc
}

bank.rest ..> bank.core
bank.rest ..> bank.persistence
bank.rest ..> jackson.databind
bank.rest ..> spring.web
bank.rest ..> spring.beans
bank.rest ..> spring.boot
bank.rest ..> spring.context
bank.rest ..> spring.boot
bank.rest ..> spring.webmvc

@enduml
