@startuml sekvensdiagram
actor Bruker
participant Ui
participant PaymentController
participant Rest
participant Core

Bruker -> Ui : Velger konto og beløp, trykker Confirm
Ui -> PaymentController : handlePayment(konto, kontonummer, beløp)

alt Input validering feilet
    PaymentController -> Ui : kaster Exception
else Input validering godkjent
    PaymentController -> Rest : sendPaymentRequest(AvsenderKontonummer, MottakerKontonummer, beløp)
    
    alt Brukervalidering feilet
        Rest -> Ui : kaster Exception
    else Brukervalidering godkjent
        Rest -> Core : payment(user, AvsenderKonto, MottakerKonto, beløp)
        Core -> Rest : bekreftelse på fullført transaksjon
        Rest -> PaymentController : bekreftelse
        PaymentController -> Ui : Fullført overføring
    end
end

Ui -> Bruker : Tilbake til hjem-skjerm med oppdatert saldo
@enduml
